# Where to load the template image from:
template_path: "${this_dir}/../templates/default.png"

# Where to load the font file from:
font_path: "${this_dir}/../fonts/EB_Garamond/EBGaramond-VariableFont_wght.ttf"

# Font size:
font_size: 40

# How many maximum characters per line before wrapping happens:
max_chars_per_line: 60

# How many maximum lines are permitted per image:
max_lines: 20

# Text color:
text_color: black

# Text position. If you set `y` to `null`, the width
# in the Y axis will be inferred and the top and bottom
# margins will be equal:
text_position: [100, null]

# Multiline spacing:
multiline_spacing: 10
