# Where to load the template image from:
template_path: "${this_dir}/../templates/default.png"

# Where to load the font file from:
font_path: "${this_dir}/../fonts/EB_Garamond/EBGaramond-VariableFont_wght.ttf"

# Font size:
font_size: 40

# How many maximum characters per line before wrapping happens:
max_chars_per_line: 60

# How many maximum lines are permitted per image:
max_lines: 20

# Text color:
text_color: black

# Text position. If you set `y` to `null`, the width
# in the Y axis will be inferred and the top and bottom
# margins will be equal:
text_position: [100, null]

# Multiline spacing:
multiline_spacing: 10

# Position of the title box:
title_position: [100, 10]

# Font to use for the title
title_font_path: "${this_dir}/../fonts/EB_Garamond/static/EBGaramond-Bold.ttf"

# Title font size:
title_font_size: 60

# Whether to write the title on all boards or just the first one
title_on_all_boards: false

# Whether to skip title
skip_title: false

# Whether to break out each stanza into a separate board:
break_stanzas: true
